name: reviewdog

# Events that trigger this workflow
on: workflow_dispatch

jobs:
  check_style:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ“¥
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Set up JDK 16 ðŸ’¿
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk

      - name: Set up reviewdog ðŸ’¿
        uses: reviewdog/action-setup@v1.0.3
        with:
          reviewdog_version: latest

      - name: Download checkstyle ðŸ“š
        run: wget -O - -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.36.2/checkstyle-8.36.2-all.jar > checkstyle.jar

      - name: Run checkstyle ðŸ“‘
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: java -jar checkstyle.jar . -c .github/workflows/checkstyle.xml -f xml | reviewdog -f=checkstyle -fail-on-error=false -level=warning -reporter=github-pr-review -filter-mode=added
